---
# Title: Authentik
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: tasks/main.yml
#
# Description:
#   authentik is an open-source Identity Provider focused on flexibility and versatility.
#

- hosts: 127.0.0.1
  connection: local
  become: true

  pre_tasks:
    #- name: "Include defaults file defaults/main.yml"
    #  include_vars: defaults/main.yml

    - name: "Include defaults file /root/.ansible-config.yml"
      include_vars: /root/.ansible-config.yml
    
  vars:
    # -- SMTP settings --
    # 
    auth_email_host                : 'localhost'
    auth_email_port                : '587'
    auth_email_username            : 'user@example.com'
    auth_email_password            : 'Welcome123'
    auth_email_use_tls             : 'false'
    auth_email_use_ssl             : 'false'
    auth_email_timeout             : '10'
    auth_email_from                : 'authentik@localhost'

    # -- GeoIP settings --
    #
    auth_geopipupdate_account_id   : '*your account ID*'
    auth_geopipupdate_license_key  : '* your license key*'
    auth_authentik_authentik_geoip : '/geoip/GeoLite2-City.mmdb'
  
  handlers:
    
  roles:
  
  tasks:
    #- name: "Include tasks/main.yml"
    #  include_tasks: tasks/main.yml
 


