---
# Title: Authentik
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: tasks/main.yml
#
# Description:
#   authentik is an open-source Identity Provider focused on flexibility and versatility.
#

- hosts: 127.0.0.1
  connection: local
  become: true

  pre_tasks:
    - name: "Include defaults file defaults/main.yml"
      include_vars: defaults/main.yml
      
  vars:
    auth_email_port                : '587'
  
  handlers:
    
  roles:
  
  tasks:
    - name: "Include tasks/main.yml"
      include_tasks: tasks/main.yml
 


