---
# Title: Authentik
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: tasks/main.yml
#
# Description:
#   authentik is an open-source Identity Provider focused on flexibility and versatility.
#
# Source(s):
#   - https://goauthentik.io/docs/installation/docker-compose
#   - https://www.serverlab.ca/tutorials/linux/web-servers-linux/how-to-reverse-proxy-websockets-with-apache-2-4/

- hosts: 127.0.0.1
  connection: local
  become: true

  pre_tasks:
    #- name: "Include defaults file defaults/main.yml"
    #  include_vars: defaults/main.yml

    - name: "Include defaults file /root/.ansible-config.yml"
      include_vars: /root/.ansible-config.yml
    
  vars:
    # -- SMTP settings --
    # 
    auth_email_host                : 'localhost'
    auth_email_port                : '587'
    auth_email_username            : 'user@example.com'
    auth_email_password            : 'Welcome123'
    auth_email_use_tls             : 'false'
    auth_email_use_ssl             : 'false'
    auth_email_timeout             : '10'
    auth_email_from                : 'authentik@localhost'

    # -- GeoIP settings --
    #
    auth_geopipupdate_account_id   : '*your account ID*'
    auth_geopipupdate_license_key  : '* your license key*'
    auth_authentik_authentik_geoip : '/geoip/GeoLite2-City.mmdb'
  
    # -- role-certbot-nginx settings --
    certbot_servername             : 'bitfinity.nl'
    certbot_serveralias            : 'auth.bitfinity.nl'
    certbot_serveradmin            : 'support@bitfinity.nl'
    certbot_documentroot           : '/var/www/html'
    
    # -- Nginx settings --
    nginx_server_name              : '{{ certbot_servername }}'
    nginx_server_alias             : '{{ certbot_serveralias }}'
    nginx_server_cert_file         : '/etc/letsencrypt/live/{{ certbot_serveralias }}/fullchain.pem'
    nginx_server_cert_key_file     : '/etc/letsencrypt/live/{{ certbot_serveralias }}/privkey.pem'

  handlers:
    - include: handlers/main.yml
    
  roles:
    #- role-certbot-apache2
    - role-certbot-nginx
    
  tasks:
    - name: "Include tasks/01-authentik.yml"
      include_tasks: tasks/01-authentik.yml
 
    - name: "Include tasks/02-nginx.yml"
      include_tasks: tasks/02-nginx.yml
