---
# Title: Authentik
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: tasks/02-apache2.yml
#
# Description:
#   authentik is an open-source Identity Provider focused on flexibility and versatility.
#
- name: "Install APT packages"
  apt:
    pkg:
    - nginx

- name: "Transfer templates"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'templates/authentik.conf.j2', dest: '/etc/nginx/sites-available/{{ certbot_serveralias }}.conf' }

- name: "Enable {{ certbot_serveralias }}.conf"
  file:
    src: /etc/nginx/sites-available/{{ certbot_serveralias }}.conf
    dest: /etc/nginx/sites-enabled/{{ certbot_serveralias }}.conf
    state: link


