---
# Title: Authentik
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: tasks/main.yml
#
# Description:
#   Authentik is an open-source Identity Provider focused on flexibility and versatility.
#
- name: "Include tasks/01-authentik.yml"
  include_tasks: tasks/01-authentik.yml

- name: "Include tasks/02-nginx.yml"
  include_tasks: tasks/02-nginx.yml
