---
# Title: Authentik
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: tasks/main.yml
#
# Description:
#   authentik is an open-source Identity Provider focused on flexibility and versatility.
#
# Source(s):
#   - https://goauthentik.io/docs/installation/docker-compose

- name: "Install APT packages"
  apt:
    pkg:
    - docker
    - docker-compose
    - docker.io
    - python3-docker
    - pwgen
    
- name: "Create directory for local authentik /opt/authentik/"
  file:
    path: /opt/authentik/
    state: directory

- name: "Download docker-compose.yml to /opt/authentik/docker-compose.yml"
  ansible.builtin.get_url:
    url: https://goauthentik.io/docker-compose.yml
    dest: /opt/authentik/docker-compose.yml
    
#- name: "Pull Docker image authentik"
#  docker_image:
#    name:  vaultwarden/server:latest
#    source: pull
