---
# Title: Authentik
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: tasks/main.yml
#
# Description:
#   authentik is an open-source Identity Provider focused on flexibility and versatility.
#
# Source(s):
#   - https://goauthentik.io/docs/installation/docker-compose

- name: "Install APT packages"
  apt:
    pkg:
    - docker
    - docker-compose
    - docker.io
    - python3-docker
    - pwgen
    
- name: "Create directory for local authentik /opt/authentik/"
  file:
    path: /opt/authentik/
    state: directory

- name: "Download docker-compose.yml to /opt/authentik/docker-compose.yml"
  ansible.builtin.get_url:
    url: https://goauthentik.io/docker-compose.yml
    dest: /opt/authentik/docker-compose.yml

- name: "Check if /opt/authentik/.env exist(s)"
  stat:
    path: /opt/authentik/.env
  register: result_env
  
- name: "Generate password for Authentik when /opt/authentik/.env does not exists (Fresh install)"
  raw: "{{ item }}"
  with_items:
    - 'echo "PG_PASS=$(pwgen -s 40 1)" >> /opt/authentik/.env'
    - 'echo "AUTHENTIK_SECRET_KEY=$(pwgen -s 50 1)" >> /opt/authentik/.env'
    - 'echo "AUTHENTIK_ERROR_REPORTING__ENABLED=true" >> /opt/authentik/.env'
  when: not result_env.stat.exists
  
#- name: "Pull Docker image authentik"
#  docker_image:
#    name:  vaultwarden/server:latest
#    source: pull

- name: "Configure E-mail configuration, /opt/authentik/.env"
  ansible.builtin.blockinfile:
    path: /opt/authentik/.env
    marker: "#<!-- {mark} ANSIBLE MANAGED BLOCK - E-mail configuration -->"
    insertafter: "#<!-- END ANSIBLE MANAGED BLOCK - E-mail configuration -->"
    block: |2
      # SMTP Host Emails are sent to
      AUTHENTIK_EMAIL__HOST="{{ auth_email_host }}"
      AUTHENTIK_EMAIL__PORT="{{ auth_email_port }}"
      # Optionally authenticate (don't add quotation marks to your password)
      AUTHENTIK_EMAIL__USERNAME="{{ auth_email_username }}"
      AUTHENTIK_EMAIL__PASSWORD="{{ auth_email_password }}"
      # Use StartTLS
      AUTHENTIK_EMAIL__USE_TLS="{{ auth_email_use_tls }}"
      # Use SSL
      AUTHENTIK_EMAIL__USE_SSL="{{ auth_email_use_ssl }}"
      AUTHENTIK_EMAIL__TIMEOUT="{{ auth_email_timeout }}"
      # Email address authentik will send from, should have a correct @domain
      AUTHENTIK_EMAIL__FROM="{{ auth_email_from }}"
#  notify: restart_apache2

- name: "Configure GeoIP configuration, /opt/authentik/.env"
  ansible.builtin.blockinfile:
    path: /opt/authentik/.env
    marker: "#<!-- {mark} ANSIBLE MANAGED BLOCK - GeoIP configuration -->"
    insertafter: "#<!-- END ANSIBLE MANAGED BLOCK - GeoIP configuration -->"
    block: |2
      GEOIPUPDATE_ACCOUNT_ID="{{ auth_geopipupdate_account_id }}"
      GEOIPUPDATE_LICENSE_KEY="{{ auth_geopipupdate_license_key }}"
      AUTHENTIK_AUTHENTIK__GEOIP="{{ auth_authentik_authentik_geoip }}"
 # notify: restart_apache2
