---
# Title: Authentik
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: handlers/main.yml
#
# Description:
#   authentik is an open-source Identity Provider focused on flexibility and versatility.
#
- name: "restart_apache2"
  systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: nginx

- name: "reload_apache2"
  systemd:
    daemon_reload: yes
    name: nginx
